import type { AlertItem, AreaInfo, DashboardStat, Trip } from "./types";

export const dashboardStats: DashboardStat[] = [
  {
    id: "drc-time",
    label: "DRC live trucks",
    value: 128,
    kpi: "orange",
    href: "/dashboard?filter=drc",
    detail: "Within / near / over KPI targets",
  },
  {
    id: "nb",
    label: "NB outstanding",
    value: 64,
    kpi: "red",
    href: "/dashboard/nb",
    detail: "Border → offload → POD",
  },
  {
    id: "sb",
    label: "SB outstanding",
    value: 52,
    kpi: "green",
    href: "/dashboard/sb",
    detail: "Loading → escort → exit",
  },
  {
    id: "pod",
    label: "POD pending",
    value: 18,
    kpi: "orange",
    href: "/dashboard/pod",
    detail: "Target 48h after offload",
  },
  {
    id: "car-docs",
    label: "Car docs expiring",
    value: 7,
    kpi: "red",
    href: "/dashboard/document-expiry?type=car",
    detail: "Vignette, insurance, pink card",
  },
  {
    id: "equip-docs",
    label: "Equipment docs expiring",
    value: 4,
    kpi: "orange",
    href: "/dashboard/document-expiry?type=equipment",
    detail: "Guarantees & certificates",
  },
];

export const liveTrips: Trip[] = [
  {
    id: "1",
    tripNumber: "NB-2026-0841",
    truck: "ABC 1234 ZM",
    owner: "TransAfrica Ltd",
    driver: "Jean Mukendi",
    direction: "NB",
    area: "Kasumbalesa",
    border: "Kasumbalesa",
    loadingPoint: "Kitwe",
    offloadingPoint: "Kolwezi Mine",
    currentStatus: "Whisky — TR8/T1 issued",
    nextAction: "Collect BAE",
    responsibleUser: "Border — Kasumbalesa",
    daysInDrc: 3,
    kpi: "orange",
    entryBorder: "Kasumbalesa",
  },
  {
    id: "2",
    tripNumber: "NB-2026-0842",
    truck: "DEF 5678 ZM",
    owner: "Copper Haul",
    driver: "Peter Banda",
    direction: "NB",
    area: "Sakania",
    border: "Sakania",
    loadingPoint: "Ndola",
    offloadingPoint: "Likasi / Tenke",
    currentStatus: "Entry card given",
    nextAction: "Issue TR8/T1 or IM4",
    responsibleUser: "Border — Sakania",
    daysInDrc: 1,
    kpi: "green",
    entryBorder: "Sakania",
  },
  {
    id: "3",
    tripNumber: "SB-2026-0312",
    truck: "GHI 9012 ZM",
    owner: "ZamCargo",
    driver: "Samuel Phiri",
    direction: "SB",
    area: "Kolwezi",
    border: "Kasumbalesa",
    loadingPoint: "Kolwezi Mine",
    offloadingPoint: "Kitwe",
    currentStatus: "Loaded — seal ready",
    nextAction: "Dispatch / escort",
    responsibleUser: "Loading — Kolwezi",
    daysInDrc: 6,
    kpi: "red",
    exitBorder: "Kasumbalesa",
  },
  {
    id: "4",
    tripNumber: "NB-2026-0839",
    truck: "JKL 3456 ZM",
    owner: "TransAfrica Ltd",
    driver: "David Chirwa",
    direction: "NB",
    area: "Kanyaka",
    border: "Mokambo",
    loadingPoint: "Lusaka",
    offloadingPoint: "Lubumbashi / Kipushi",
    currentStatus: "Arrived Kanyaka — weighed",
    nextAction: "POD received at Kanyaka",
    responsibleUser: "Kanyaka Team",
    daysInDrc: 11,
    kpi: "orange",
    entryBorder: "Mokambo",
  },
  {
    id: "5",
    tripNumber: "SB-2026-0310",
    truck: "MNO 7890 ZM",
    owner: "Copper Haul",
    driver: "Joseph Mwale",
    direction: "SB",
    area: "Kanyaka",
    border: "Sakania",
    loadingPoint: "Kambove / Kisanfu",
    offloadingPoint: "Ndola",
    currentStatus: "Following-on — Mutaka",
    nextAction: "Complete Mutaka ≤ 2h",
    responsibleUser: "Following-on List",
    daysInDrc: 9,
    kpi: "red",
    exitBorder: "Sakania",
  },
  {
    id: "6",
    tripNumber: "NB-2026-0835",
    truck: "PQR 1122 ZM",
    owner: "ZamCargo",
    driver: "Eric Tembo",
    direction: "NB",
    area: "Kolwezi",
    border: "Kasumbalesa",
    loadingPoint: "Kitwe",
    offloadingPoint: "Kolwezi Mine",
    currentStatus: "Mine arrival — offloading",
    nextAction: "Collect POD",
    responsibleUser: "Offloading — Kolwezi",
    daysInDrc: 13,
    kpi: "red",
    entryBorder: "Kasumbalesa",
  },
];

export const priorityAlerts: AlertItem[] = [
  {
    id: "a1",
    level: "orange",
    truck: "ABC 1234 ZM",
    trip: "NB-2026-0841",
    area: "Kasumbalesa",
    process: "Whisky BAE collection",
    nextAction: "Collect BAE (target 24h)",
    timeRemaining: "4h remaining",
  },
  {
    id: "a2",
    level: "red",
    truck: "GHI 9012 ZM",
    trip: "SB-2026-0312",
    area: "Kolwezi",
    process: "Dispatch / escort",
    nextAction: "Assign escort and dispatch",
    timeRemaining: "2 days overdue",
  },
  {
    id: "a3",
    level: "red",
    truck: "MNO 7890 ZM",
    trip: "SB-2026-0310",
    area: "Kanyaka",
    process: "Following-on Mutaka",
    nextAction: "Clear Mutaka list ≤ 2h",
    timeRemaining: "1h 20m overdue",
  },
];

export const areas: AreaInfo[] = [
  { slug: "kasumbalesa", name: "Kasumbalesa", direction: "Both", liveNb: 22, liveSb: 14, overdue: 5 },
  { slug: "kanyaka", name: "Kanyaka", direction: "Both", liveNb: 11, liveSb: 9, overdue: 3 },
  { slug: "lubumbashi-kipushi", name: "Lubumbashi / Kipushi", direction: "Both", liveNb: 8, liveSb: 6, overdue: 1 },
  { slug: "likasi-tenke", name: "Likasi / Tenke", direction: "Both", liveNb: 7, liveSb: 5, overdue: 2 },
  { slug: "kambove-kisanfu", name: "Kambove / Kisanfu", direction: "Both", liveNb: 6, liveSb: 8, overdue: 2 },
  { slug: "kolwezi", name: "Kolwezi", direction: "Both", liveNb: 10, liveSb: 10, overdue: 4 },
  { slug: "unassigned", name: "Unassigned Area", direction: "Both", liveNb: 2, liveSb: 1, overdue: 0 },
];

export const borderStatuses = {
  sakania: [
    "Truck crossed into DRC Lukangaba Parking",
    "Entry card given to clearing agent",
    "TR8/T1 or IM4 issued",
    "Full set of documents collected",
    "Brigade stamp put on document",
    "Seal collected",
    "Parking penalty requested",
    "Parking penalty sent",
    "Parking penalty paid",
    "Documents handed to driver",
  ],
  mokambo: [
    "Truck crossed into DRC Mokambo Parking",
    "Entry card given to clearing agent",
    "TR8/T1 or IM4 issued",
    "Full set of documents collected",
    "Brigade stamp put on document",
    "Seal collected",
    "Parking penalty requested",
    "Parking penalty sent",
    "Parking penalty paid",
    "Documents handed to driver",
  ],
  kasumbalesa: {
    kbp: [
      "Truck crossed into DRC KBP Parking",
      "Submission of documents (Titre & POD) to Brigade (ETC 4h)",
      "Truck scanning completed",
      "Runner took docs for green stamping (ETC 1h)",
      "Red stamping by customs inspector (ETC 1h)",
      "Cross-checking in customs control room",
      "Driver WhatsApp / DRC current number",
    ],
    whisky: [
      "Entry card given to clearing agent",
      "Truck scanning completed (result after 24h)",
      "TR8/T1 or IM4 issued",
      "Duty payment made (IM4)",
      "BAE collection (ETC 24h)",
      "SEGUCE payment",
      "Bon de sortie generation (ETC 2h)",
      "Brigade stamp put on document",
      "Full set of documents collected",
      "Seal collected (TR8/T1)",
      "Parking penalty requested / sent / paid",
      "Documents handed to driver",
    ],
  },
} as const;

export const sbLoadingStatuses = [
  "Truck arrives at mine",
  "Date planned to load",
  "Date loaded",
  "Document ready",
  "Seal ready",
  "Dispatched",
  "Escort arrives",
  "Left the mine",
] as const;

export const runnerFeeRules = [
  { border: "Sakania / Kasumbalesa", days: "0–2 days", rate: 40, group: "Yellow" },
  { border: "Sakania / Kasumbalesa", days: "3–4 days", rate: 25, group: "Blue" },
  { border: "Sakania / Kasumbalesa", days: "5+ days", rate: 15, group: "Red" },
  { border: "Kanyaka NB", days: "0–1 day", rate: 5, group: "Kanyaka" },
  { border: "Kanyaka NB", days: "2+ days", rate: 0, group: "Kanyaka" },
  { border: "Kanyaka SB", days: "0–1 day", rate: 5, group: "Kanyaka" },
  { border: "Kanyaka SB", days: "2+ days", rate: 0, group: "Kanyaka" },
] as const;

export const reportCatalog = [
  { name: "All KPIs", href: "/reports/kpi", description: "Targets, achievements, overdues by area and user" },
  { name: "NB Turnaround", href: "/reports/nb", description: "All areas, per area, per user" },
  { name: "SB Turnaround", href: "/reports/sb", description: "All areas, per area, per user" },
  { name: "DRC User Turnaround", href: "/reports/kpi", description: "All users, per user, all DRC" },
  { name: "POD Report", href: "/reports/pod", description: "Collection, upload, invoice handover" },
  { name: "Cars with documentation", href: "/reports/assets", description: "Documents, dates, expiry status" },
  { name: "Cars with maintenance", href: "/reports/assets", description: "Issues, garage, cost, guarantee" },
  { name: "All equipment", href: "/reports/assets", description: "Assignment, maintenance, return status" },
  { name: "Communication matrix", href: "/reports/communication", description: "All / per area / per company" },
  { name: "Runner fee report", href: "/reports/runner-fee", description: "Groups, subtotals, grand total" },
  { name: "Audit report", href: "/reports/audit", description: "Edits, deletes, uploads, exports" },
] as const;
