/**
 * Report print & PDF export — shared by custom-reports.js
 */
(function () {
    function escapeHtml(s) {
        return String(s ?? '—')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }

    function sanitizeFilename(name) {
        return String(name || 'report').replace(/[^\w\-]+/g, '_').slice(0, 80);
    }

    function buildPrintHtml(title, headers, rows, subtitle) {
        const head = headers.map(h => `<th>${escapeHtml(h)}</th>`).join('');
        const body = rows.map(row => `<tr>${row.map(c => `<td>${escapeHtml(c)}</td>`).join('')}</tr>`).join('');
        const brand = typeof APP_BRAND_NAME !== 'undefined' ? APP_BRAND_NAME : 'TruckControl';
        return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
@page { margin: 12mm; }
body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #111; margin: 16px; }
h1 { font-size: 18px; margin: 0 0 4px; }
.meta { color: #555; font-size: 10px; margin-bottom: 14px; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #ccc; padding: 5px 7px; text-align: left; vertical-align: top; }
th { background: #f0f4f8; font-weight: 600; }
tr:nth-child(even) td { background: #fafafa; }
.footer { margin-top: 12px; font-size: 9px; color: #888; }
</style></head><body>
<h1>${escapeHtml(title)}</h1>
<div class="meta">${escapeHtml(subtitle || '')}<br>${brand} · ${new Date().toLocaleString()}</div>
<table><thead><tr>${head}</tr></thead><tbody>${body || '<tr><td colspan="' + headers.length + '">No data</td></tr>'}</tbody></table>
<div class="footer">Generated by ${brand} Reports</div>
</body></html>`;
    }

    function openPrintWindow(title, headers, rows, subtitle) {
        if (!headers?.length) {
            if (typeof showToast === 'function') showToast('No columns to print', 'warning');
            return;
        }
        const popup = window.open('', '_blank', 'noopener,noreferrer,width=1100,height=800');
        if (!popup) {
            if (typeof showToast === 'function') showToast('Allow pop-ups to print reports', 'warning');
            return;
        }
        popup.document.open();
        popup.document.write(buildPrintHtml(title, headers, rows, subtitle));
        popup.document.close();
        popup.onload = () => setTimeout(() => { try { popup.focus(); popup.print(); } catch (_) {} }, 350);
    }

    function exportPdf(title, headers, rows, filenamePrefix) {
        if (!headers?.length) {
            if (typeof showToast === 'function') showToast('No columns to export', 'warning');
            return;
        }
        if (!rows?.length) {
            if (typeof showToast === 'function') showToast('No data to export', 'warning');
            return;
        }
        const jspdf = window.jspdf;
        if (!jspdf?.jsPDF) {
            if (typeof showToast === 'function') showToast('PDF library loading — try again in a moment', 'warning');
            return;
        }
        const landscape = headers.length > 7;
        const doc = new jspdf.jsPDF({ orientation: landscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
        const brand = typeof APP_BRAND_NAME !== 'undefined' ? APP_BRAND_NAME : 'TruckControl';
        doc.setFontSize(14);
        doc.text(title, 14, 14);
        doc.setFontSize(9);
        doc.text(`${brand} · ${new Date().toLocaleString()}`, 14, 20);
        const tableBody = rows.map(r => r.map(c => String(c ?? '—')));
        if (typeof doc.autoTable === 'function') {
            doc.autoTable({
                head: [headers],
                body: tableBody,
                startY: 26,
                styles: { fontSize: landscape ? 7 : 8, cellPadding: 2 },
                headStyles: { fillColor: [45, 55, 72] },
                margin: { left: 10, right: 10 }
            });
        } else {
            doc.text('PDF table plugin not loaded', 14, 30);
        }
        const stamp = typeof formatExportDate === 'function' ? formatExportDate() : Date.now();
        doc.save(`${sanitizeFilename(filenamePrefix || title)}_${stamp}.pdf`);
        if (typeof showToast === 'function') showToast('PDF downloaded', 'success');
    }

    window.printReportTable = function (title, headers, rows, subtitle) {
        openPrintWindow(title, headers, rows, subtitle);
    };

    window.exportReportPdf = function (title, headers, rows, filenamePrefix) {
        exportPdf(title, headers, rows, filenamePrefix);
    };

    window.buildReportPrintPayload = function (title, cols, dataRows) {
        const headers = (cols || []).map(c => c.label);
        const rows = (dataRows || []).map(r => (cols || []).map(c => {
            const v = c.getValue(r);
            return v == null ? '—' : String(v);
        }));
        return { title, headers, rows };
    };
})();
