import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = "/api";
const api = async (path, options = {}, token) => {
  const isForm = options.body instanceof FormData;
  const r = await fetch(API + path, { ...options, headers: { ...(isForm ? {} : {"Content-Type":"application/json"}), ...(token ? {Authorization:`Bearer ${token}`} : {} } });
  const data = r.headers.get("content-type")?.includes("application/json") ? await r.json() : r;
  if (!r.ok) throw new Error(data.error || "Request failed");
  return data;
};
const statusOptions = ["Arrived at border","TR8/T1 issued","IM4 issued","Documents handed to driver","Arrived at Kanyaka","Arrived at mine","Loading planned","Loaded","Dispatch ready","POD collected","POD uploaded","POD sent to invoice team","Exited to Zambia"];

function Login({onLogin}) {
  const [email,setEmail]=useState("admin@turnaround.local"),[password,setPassword]=useState("ChangeMe123!"),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const submit=async e=>{e.preventDefault();setLoading(true);try{onLogin(await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})}));}catch(e){setError(e.message)}finally{setLoading(false)}};
  return <main className="login"><section><div className="brand"><span>TC</span><div><strong>Turnaround Control</strong><small>DRC Operations Control System</small></div></div><h1>Welcome back</h1><p>Sign in to coordinate live truck operations.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<p className="error">{error}</p>}<button disabled={loading}>{loading?"Signing in…":"Sign in"}</button></form><p className="hint">Demo administrator: admin@turnaround.local / ChangeMe123!</p></section></main>
}
function Badge({level}) { return <span className={`badge ${level}`}>{level==="red"?"Overdue":level==="orange"?"Priority":"On time"}</span> }
function Dashboard({token,setPage}) {
 const [d,setD]=useState(); useEffect(()=>{api("/dashboard",{},token).then(setD)},[token]); if(!d)return <div className="loader">Loading control tower…</div>;
 const cards=[["Live trucks",d.total,"neutral"],["North Bound",d.nb,"blue"],["South Bound",d.sb,"purple"],["On time",d.green,"green"],["Priority",d.orange,"orange"],["Overdue",d.red,"red"]];
 return <><div className="title"><div><h1>Control tower</h1><p>Live operational position across DRC</p></div><button onClick={()=>setPage("new-trip")}>+ Add truck</button></div><div className="cards">{cards.map(([a,b,c])=><button key={a} className={`card ${c}`} onClick={()=>setPage("trips")}><small>{a}</small><strong>{b}</strong></button>)}</div><section className="grid"><div className="panel"><h2>Priority worklist</h2>{d.alerts.length?d.alerts.map(t=><div className="alert-row" key={t.id}><Badge level={t.level}/><div><strong>{t.truck_number} · {t.trip_number}</strong><small>{t.area} · {t.current_status}</small></div><b>{t.hours}h</b></div>):<Empty text="No priority alerts. All trucks are within target."/>}</div><div className="panel"><h2>Live operations by area</h2>{d.perArea.map((a,i)=><div className="area-row" key={i}><span>{a.area}</span><small>{a.direction}</small><b>{a.count}</b></div>)}{!d.perArea.length&&<Empty text="Area counts will appear as trips are created."/>}</div></section></>
}
function Empty({text}) {return <p className="empty">{text}</p>}
function Trips({token,direction,openTrip}) {
 const [trips,setTrips]=useState([]),[q,setQ]=useState(""); const load=()=>api(`/trips?live=true${direction?`&direction=${direction}`:""}&q=${encodeURIComponent(q)}`,{},token).then(setTrips); useEffect(load,[direction,token]); 
 return <><div className="title"><div><h1>{direction?`${direction} live operations`:"Live operations"}</h1><p>Search, prioritize, and update active truck workflows.</p></div></div><div className="toolbar"><input placeholder="Search truck, trip, owner, driver…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button className="secondary" onClick={load}>Search</button></div><div className="panel table-wrap"><table><thead><tr><th>Truck / Trip</th><th>Direction</th><th>Area</th><th>Current status</th><th>Time in DRC</th><th>KPI</th><th/></tr></thead><tbody>{trips.map(t=><tr key={t.id}><td><strong>{t.truck_number}</strong><small>{t.trip_number} · {t.owner||"No owner"}</small></td><td>{t.direction}</td><td>{t.area}</td><td>{t.current_status}</td><td>{t.hours}h / {t.kpiHours}h</td><td><Badge level={t.level}/></td><td><button className="link" onClick={()=>openTrip(t.id)}>Open</button></td></tr>)}</tbody></table>{!trips.length&&<Empty text="No live trips found."/>}</div></>
}
function NewTrip({token,done}) {
 const [v,setV]=useState({direction:"NB",area:"Unassigned",started_at:new Date().toISOString().slice(0,16)}),[err,setErr]=useState("");const f=(label,key,type="text")=><label>{label}<input type={type} value={v[key]||""} onChange={e=>setV({...v,[key]:e.target.value})}/></label>;
 const submit=async e=>{e.preventDefault();try{await api("/trips",{method:"POST",body:JSON.stringify({...v,started_at:new Date(v.started_at).toISOString()})},token);done();}catch(e){setErr(e.message)}};
 return <><div className="title"><div><h1>Add live truck</h1><p>Create one operational record for a Trip + Truck.</p></div></div><form className="panel form" onSubmit={submit}><div className="form-grid">{f("Trip number *","trip_number")}{f("Truck number *","truck_number")}<label>Direction *<select value={v.direction} onChange={e=>setV({...v,direction:e.target.value})}><option>NB</option><option>SB</option></select></label>{f("Owner","owner")}{f("Driver","driver_name")}{f("Driver phone","driver_phone")}<label>Area<select value={v.area} onChange={e=>setV({...v,area:e.target.value})}><option>Unassigned</option>{["Kasumbalesa","Sakania","Mokambo","Kanyaka","Lubumbashi / Kipushi","Likasi / Tenke","Kambove / Kisanfu","Kolwezi"].map(x=><option key={x}>{x}</option>)}</select></label>{f("Loading point","loading_point")}{f("Offloading point","offloading_point")}{f("Entry border","entry_border")}{f("Exit border","exit_border")}{f("Start time","started_at","datetime-local")}</div>{err&&<p className="error">{err}</p>}<button>Create live trip</button></form></>
}
function TripProfile({token,id,back}) {
 const [data,setData]=useState(),[status,setStatus]=useState({status:"",event_at:new Date().toISOString().slice(0,16)}),[err,setErr]=useState(""),[file,setFile]=useState(null),[docType,setDocType]=useState("POD"); const load=()=>api(`/trips/${id}`,{},token).then(setData);useEffect(load,[id]);if(!data)return <div className="loader">Loading trip…</div>;
 const save=async e=>{e.preventDefault();try{await api(`/trips/${id}/statuses`,{method:"POST",body:JSON.stringify({...status,event_at:new Date(status.event_at).toISOString()})},token);setStatus({status:"",event_at:new Date().toISOString().slice(0,16)});load()}catch(e){setErr(e.message)}};
 const upload=async e=>{e.preventDefault();if(!file)return;const fd=new FormData();fd.append("file",file);fd.append("document_type",docType);await api(`/trips/${id}/documents`,{method:"POST",body:fd},token);setFile(null);load()};
 const t=data.trip;return <><button className="back" onClick={back}>← Back to worklist</button><div className="title profile-title"><div><h1>{t.truck_number} <small>· {t.trip_number}</small></h1><p>{t.direction} · {t.area} · {t.owner||"No owner"} <Badge level={t.level}/></p></div><div className="hours">{t.hours}h <small>in DRC</small></div></div><section className="grid profile"><form className="panel" onSubmit={save}><h2>Update workflow status</h2><label>Status<select required value={status.status} onChange={e=>setStatus({...status,status:e.target.value})}><option value="">Select status…</option>{statusOptions.map(s=><option key={s}>{s}</option>)}</select></label><label>Event time<input type="datetime-local" value={status.event_at} onChange={e=>setStatus({...status,event_at:e.target.value})}/></label><label>Problem<textarea value={status.problem||""} onChange={e=>setStatus({...status,problem:e.target.value})}/></label><label>Person contacted<input value={status.person_contacted||""} onChange={e=>setStatus({...status,person_contacted:e.target.value})}/></label><label>Action taken<textarea value={status.action_taken||""} onChange={e=>setStatus({...status,action_taken:e.target.value})}/></label><label>Expected solution time<input type="datetime-local" value={status.expected_at||""} onChange={e=>setStatus({...status,expected_at:e.target.value})}/></label>{err&&<p className="error">{err}</p>}<button>Save status update</button></form><div className="panel"><h2>Documents</h2><form className="doc-form" onSubmit={upload}><select value={docType} onChange={e=>setDocType(e.target.value)}>{["T1","TR8","IM4","POD","Invoice","CEEC","LMC","Parking Ticket","Entry Card","EXP1","Packing List","COD","Police Report","Insurance","Other"].map(x=><option key={x}>{x}</option>)}</select><input type="file" onChange={e=>setFile(e.target.files[0])}/><button>Upload</button></form>{data.documents.map(d=><a className="document" key={d.id} href={`/uploads/${d.filename}`} target="_blank">{d.document_type}<small>{d.original_filename}</small></a>)}{!data.documents.length&&<Empty text="No documents uploaded."/>}<h2 className="timeline-title">Timeline</h2>{data.timeline.map(e=><div className="timeline" key={e.id}><span></span><div><strong>{e.status}</strong><small>{new Date(e.event_at).toLocaleString()} · {e.entered_by_name}</small>{e.problem&&<p><b>Problem:</b> {e.problem}<br/><b>Action:</b> {e.action_taken}</p>}</div></div>)}{!data.timeline.length&&<Empty text="No status updates yet."/>}</div></section></>
}
function Import({token}) { const [file,setFile]=useState(),[result,setResult]=useState(); const send=async e=>{e.preventDefault();const fd=new FormData();fd.append("file",file);setResult(await api("/imports/trips",{method:"POST",body:fd},token));};return <><div className="title"><div><h1>Import daily operations</h1><p>Import only new Trip + Truck + Direction records from Excel.</p></div></div><form className="panel import" onSubmit={send}><p>Required headers: <code>Trip</code>, <code>Truck</code>, <code>Direction</code>. Optional: Owner, Driver, Loading Point, Offloading Point, Area, Entry Border, Exit Border.</p><input required type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files[0])}/><button>Validate & import</button></form>{result&&<div className="panel"><h2>Import results</h2><p><b>{result.created}</b> of {result.total} records imported.</p>{result.errors.map((e,i)=><p className="error" key={i}>Row {e.row}: {e.error}</p>)}</div>}</>}
function Reports({token}) { const [r,setR]=useState();useEffect(()=>api("/reports/turnaround",{},token).then(setR),[token]);return <><div className="title"><div><h1>Turnaround reports</h1><p>Historical operational performance and completed trips.</p></div><a className="button" href={`${API}/reports/turnaround.xlsx`} onClick={e=>{e.preventDefault();fetch(`${API}/reports/turnaround.xlsx`,{headers:{Authorization:`Bearer ${token}`}}).then(x=>x.blob()).then(b=>{const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="turnaround-report.xlsx";a.click()})}}>Export Excel</a></div>{r&&<><div className="cards"><div className="card neutral"><small>All records</small><strong>{r.summary.total}</strong></div><div className="card blue"><small>NB records</small><strong>{r.summary.nb}</strong></div><div className="card purple"><small>SB records</small><strong>{r.summary.sb}</strong></div><div className="card green"><small>Completed</small><strong>{r.summary.completed}</strong></div></div><div className="panel table-wrap"><table><thead><tr><th>Truck / Trip</th><th>Direction</th><th>Area</th><th>Status</th><th>Started</th><th>Completed</th></tr></thead><tbody>{r.trips.map(t=><tr key={t.id}><td><strong>{t.truck_number}</strong><small>{t.trip_number}</small></td><td>{t.direction}</td><td>{t.area}</td><td>{t.current_status}</td><td>{new Date(t.started_at).toLocaleDateString()}</td><td>{t.completed_at?new Date(t.completed_at).toLocaleDateString():"Live"}</td></tr>)}</tbody></table></div></>}</>}
function App(){const [session,setSession]=useState(()=>JSON.parse(localStorage.getItem("session")||"null")),[page,setPage]=useState("dashboard"),[trip,setTrip]=useState();if(!session)return <Login onLogin={x=>{localStorage.setItem("session",JSON.stringify(x));setSession(x)}}/>;const nav=[["dashboard","Control tower"],["nb","NB operations"],["sb","SB operations"],["import","Daily import"],["reports","Reports"],["new-trip","Add truck"]];const content=trip?<TripProfile token={session.token} id={trip} back={()=>setTrip(null)}/>:page==="dashboard"?<Dashboard token={session.token} setPage={setPage}/>:page==="new-trip"?<NewTrip token={session.token} done={()=>setPage("trips")}/>:page==="import"?<Import token={session.token}/>:page==="reports"?<Reports token={session.token}/>:<Trips token={session.token} direction={page==="nb"?"NB":page==="sb"?"SB":undefined} openTrip={setTrip}/>;return <div className="app"><aside><div className="brand"><span>TC</span><div><strong>Turnaround</strong><small>CONTROL SYSTEM</small></div></div><nav>{nav.map(([id,label])=><button className={page===id?"active":""} onClick={()=>{setTrip(null);setPage(id)}} key={id}>{label}</button>)}</nav><div className="user"><strong>{session.user.name}</strong><small>{session.user.role}</small><button onClick={()=>{localStorage.removeItem("session");setSession(null)}}>Sign out</button></div></aside><main className="content">{content}</main></div>}
createRoot(document.getElementById("root")).render(<App/>);
